version: "3"

tasks:
  laravel: (cd laravel && ./vendor/bin/sail up)
  rails: (cd rails && bin/rails server)
  fastapi: (cd fastapi && pipenv run uvicorn main:app --workers $(nproc))
  shelf:jit: (cd shelf && dart bin/api.dart)
  shelf:n10: (cd shelf && dart bin/api_isolates.dart)
  shelf:exe: (cd shelf && dart compile exe bin/api.dart && bin/api.exe)
  django: (cd django && pipenv run python manage.py runserver)
  djangicorn: (cd djangicorn && pipenv run gunicorn api.asgi:application -k uvicorn.workers.UvicornWorker -w $(nproc))
